version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/data/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    command: ["yarn", "run", "dev"]
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/dev?schema=public
    depends_on:
      db:
        condition: service_healthy
networks:
  db:
    driver: bridge
volumes:
  db:
