# fly.toml app configuration file generated for todoist-integration on 2024-06-13T01:20:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todoist-integration'
primary_region = 'ord'

[build]

[deploy]
  release_command = "bash -c 'node_modules/.bin/prisma migrate deploy'"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 3000
    timeout = "10s"
    type = "http"
